### ISSUE TITLE
Image upload / insert not working

### ISSUE THREAD

**Issue by joekrump** [Samuell1/contenteditor-plugin#1]
I'm having some difficulty getting the image inserting to work with the editor. When I click the upload button on the modal that pops up, I get the file picker and choose an image. After this however, nothing happens. I don't see any request going to the server or anything else going on. No errors showing up either. Am I missing something or is this currently not implemented yet?

**Comment by samuelpatro** [comment]
It's not implemented but it's on freatures list :)
