### ISSUE TITLE
Edit text only block?

### ISSUE THREAD

**Issue by l3utterfly** [Samuell1/contenteditor-plugin#10]
Is it possible to have a setting so we can edit text-only block on the page? So you can't choose styles etc. This will be useful when you just want to edit a heading which already has a predefined style

**Comment by KirbyFox** [comment]
<code><span class="pun">{%</span><span class="pln"> placeholder ordering title</span><span class="pun">=</span><span class="str">"Ordering information"</span><span class="pln"> type</span><span class="pun">=</span><span class="str">"text"</span><span class="pln"> </span><span class="pun">%}</span></code>

https://octobercms.com/docs/markup/tag-placeholder

**Comment by samuelpatro** [comment]
@l3utterfly Hey, i have good news, i try something and its working! :)

With this you can define your "fixture" tag and it get converted to that specific tag without toolbox (only allowed redo, undo, delete)

```
{% component 'contenteditor' file="welcome.htm" fixture="h3" %}
```

**Comment by samuelpatro** [comment]
@l3utterfly You can check commit for it :) https://github.com/Samuell1/contenteditor/commit/afc1cbe95f66bdb3555463d6d4e677cdd9b8b385
