### ISSUE TITLE
Class property bug with multiple instances of contenteditor

### ISSUE THREAD

**Issue by jonathan-hc** [Samuell1/contenteditor-plugin#101]
**Issue:** If there are multiple contenteditor instances in a template and one of them uses the class property, the value for the property gets applied to all the instances that follow it in the template.
**Workaround:** We need to reset the class property by adding an empty class property to all the following instances of content builder
**ContentEditor Version:** 1.3.1
**OctoberCMS Build:** 467

**Comment by samuelpatro** [comment]
Duplicate of #81
