### ISSUE TITLE
Allow empty content file

### ISSUE THREAD

**Issue by Conobi** [Samuell1/contenteditor-plugin#102]
Hi,
On the backend UI, when adding a contenteditor component we are required to choose a content file, even if it is optional. That's weird, as I need it only to integrate content as fixtures
Here is what I mean:
![Screenshot](https://user-images.githubusercontent.com/5563277/88922534-86535600-d270-11ea-8e6e-d43c8924ebf9.png)

Thanks for your work though!

**Comment by samuelpatro** [comment]
Hey, you can ignore it there and define your file path and name in tag in code.
