### ISSUE TITLE
Style palettes not appearing in front-end

### ISSUE THREAD

**Issue by WC-Jordy** [Samuell1/contenteditor-plugin#103]
I'd like to make use of style palettes to add an emphasis to parts of text or headings. I've set it up like this:
![image](https://user-images.githubusercontent.com/69194376/93598687-577a7600-f9bd-11ea-95ea-419bcfb33896.png)

However in the front-end, the styles do not show up:
![image](https://user-images.githubusercontent.com/69194376/93598785-7da01600-f9bd-11ea-8671-e3b1e90afb68.png)

**Comment by samuelpatro** [comment]
Hey, can you check in your website source code if there is anything related to palettes?
