### ISSUE TITLE
Not work in snippet - AJAX handler 'contenteditor::onSave' was not found.

### ISSUE THREAD

**Issue by point111** [Samuell1/contenteditor-plugin#106]
I need editable txt for "Static Pages".

Partial/snippet can be set in a "Static Pages"  and in this snippet I am installing the "contenteditor" component. 

But when I click the "save" button, the message 'contenteditor :: onSave' was not found is displayed.

In the main layout included:
<script src="{{'assets/js/jquery.3.5.1.min.js'|theme}}"></script>
{% framework %} 
{% scripts %}
{% styles %}

**Comment by samuelpatro** [comment]
I think its same limitation like this https://github.com/Samuell1/contenteditor-plugin/issues/64

**Comment by point111** [comment]
Is it possible to use "Сontenteditor" without AJAX? Only POST?

**Comment by samuelpatro** [comment]
@point111 I dont think so because how do you otherwise send a requests to save data.
