### ISSUE TITLE
Image upload issue

### ISSUE THREAD

**Issue by waterman455** [Samuell1/contenteditor-plugin#107]
When I try to upload an image i have this error in console : 

POST http://markomtest.eu5.net/contenteditor/image/upload 404 (Not Found)
(anonymous) @ contenteditor.js:290
a.dispatchEvent @ content-tools.min.js:4
(anonymous) @ content-tools.min.js:5

I thought if I add a new upload and image folder into the plugin directory will fix the problem but it didnt , contenteditor/image/upload ,   can you help me with this issue please I cant upload a picture and when I insert it I get an animation of big X and this error ,

![image](https://user-images.githubusercontent.com/48554514/112027443-73f79680-8b37-11eb-9187-32b39e8180aa.png)

**Comment by samuelpatro** [comment]
This looks like issue with your service worker?
