### ISSUE TITLE
Disable wysiwyg editor on backend

### ISSUE THREAD

**Issue by CarolinePublipresse** [Samuell1/contenteditor-plugin#109]
Hi, 
Your plugin is awesome. Thank you.
But I'm having some trouble when editing the content files from the backend (on October2) : it now display the content in a wisiwyg editor instead of the usual code editor. It automatically adds <p> tags in the content. But when I use these contents in fixture, the consequence is that it adds some `<p>` inside the `<h2>` titles that I can't remove without editing it through the FTP.
When I edit content from the backend rather than the front, it is always to display the code, I never need this wysiwyg interface. Is there a way to disable it ? 
Thanks

**Comment by samuelpatro** [comment]
Hey, iam not sure if there is way to change this but, there should be button to switch to code editor.
