### ISSUE TITLE
JS Errors

### ISSUE THREAD

**Issue by SebastiaanKloos** [Samuell1/contenteditor-plugin#11]
I get this error when following the steps you provided. 
![screen shot 2017-02-08 at 22 57 47](https://cloud.githubusercontent.com/assets/6506510/22759276/1ddc59c4-ee52-11e6-9a28-c925fe5f0a1f.png)

**Comment by samuelpatro** [comment]
Hey, can you please provide more info (version of october, plugins ...)? Maybe something other interacts with content editor

**Comment by samuelpatro** [comment]
@SebastiaanKloos any updates on this error?
