### ISSUE TITLE
Edit Images

### ISSUE THREAD

**Issue by alexTitakoff** [Samuell1/contenteditor-plugin#110]
Hello cool plugin!

I don't understand if it is possible to edit pictures? It seems to be, but I don't understand how?

**Comment by samuelpatro** [comment]
Hello, Yes you can edit images before uploading them in editor. If they are already placed there isnt option to crop them.

**Comment by alexTitakoff** [comment]
Samuel, thank you for your time. Could you give an example of a code for editing an image?
