### ISSUE TITLE
All the buttons are greyed out

### ISSUE THREAD

**Issue by dannjoroge** [Samuell1/contenteditor-plugin#113]
Why are my buttons greyed out in octobercms i cannot use all buttons i have updated the permissions.

**Comment by samuelpatro** [comment]
Hey, do you applied witch buttons will be active in backend settings?

**Comment by dannjoroge** [comment]
> Hey, do you applied witch buttons will be active in backend settings?

yes i have image, video and table not working only bold, italic and link are working. my email njorogedan78@gmail.com

**Comment by samuelpatro** [comment]
It sometimes depends on element you want to edit for example in heading you cant add image.

**Comment by dannjoroge** [comment]
i have tried none seems to work.  the image attached shows the buttons i can access from p or div if set as a fixture. table, image, video don't seem to be clickable. the justification is available but does not work if clicked but that isn't a problem

```
[contenteditor]



==
{% component 'contenteditor' file="home_header.htm" fixture="h1"  class="my-class" %}

{% component 'contenteditor' file="home_p.htm" fixture="div"  %}


{% component 'contenteditor' file="home_table.htm" fixture="table"  %}

{% component 'contenteditor' file="filename_in_content.htm" %}
```

<img width="860" alt="Screenshot 2021-12-28 at 15 37 00" src="https://user-images.githubusercontent.com/14175889/147567040-8309cb41-1449-4a96-a3f3-d26dcd331ada.png">

**Comment by samuelpatro** [comment]
Yeah thats the limitation of fixture. You can make it work when you dont use fixture for div and p then it should work. Fixtures are mostly made for headings and stuff like that they mostly dont work correctly with other elements.
