### ISSUE TITLE
October v2 image upload

### ISSUE THREAD

**Issue by Pixinside** [Samuell1/contenteditor-plugin#114]
Hello,

It's not possible anymore to upload images with October V2.
This line should be changed in 'http/controllers/ImageController.php' line 89:
`$relativeFilePath = config('cms.storage.media.path').$filePath;`
with
`$relativeFilePath = config('system.storage.media.path').$filePath;`

**Comment by samuelpatro** [comment]
Hey, can you make PR for it will merge it release new version. Thanks!

**Comment by Pixinside** [comment]
Done! And thanks for your plugin… it’s really good!
