### ISSUE TITLE
Save not working

### ISSUE THREAD

**Issue by tleonard2** [Samuell1/contenteditor-plugin#116]
i've been using Content Editor with October with no issues and recently am converting to WinterCMS. In Winter, the Content Editor appears and allows entry but when the edit is done, it does not save but rather the gear symbol just spins.

**Comment by arvislacis** [comment]
It works fine for me but I was testing on fresh Winter CMS 1.1.8 dev build so maybe issue is more related to migration/convertion from October CMS to Winter CMS, for example, maybe something related with session cookies or Ajax handlers. I would probably recommend you to re-login into the back-end (to reset session cookies) and/or check file permissions for the content files you try to overwrite when saving - maybe plugin just hasn't permissions to save changes...

Anyways, also check if there is any error in the `console.log()` and/or back-end log.

**Comment by tleonard2** [comment]
so far no luck. i have removed and reinstalled a couple times. logged out, logged in.  i am getting this error Class name is not registered for the component "contenteditor". Check the component plugin. in /home/customer/www/portlandnursery.com/public_html/winterpn/modules/cms/classes/ComponentManager.php:204

**Comment by arvislacis** [comment]
@tleonard2 I am still thinking that maybe something is wrong with your installation, not the plugin directly, check out these resources:
- https://octobercms.com/forum/post/class-name-is-not-registered-for-the-component-works-in-local-but-fail-on-server
- https://octobercms.com/forum/post/class-name-is-not-registered-for-the-component-error-after-update-to-version-build-376

So maybe you need to change permissions of the plugin directory or check if you still have plugin installed and plugin component is attached to the layout.

**Comment by tleonard2** [comment]
this seems to be a WinterCMS problem vs an OctoberCMS problem. I installed a demo version of Winter and installed the editor using the Demo theme and it does not save. It has always worked in October. I have installed the plugin using php and using the installer. neither works to save. I checked all the permissions against the working version in October.  How did you install it in your Winter version - using the installer or with php? Also, i noticed my October version of the plugin had a composer.json file and the Winter version did not, so i tried moving that over.. Are there any plugins that the editor is depending on? any other ideas?

**Comment by arvislacis** [comment]
I have installed dev version (1.1.8 dev-main) of Winter CMS via Composer, also running  my installation on PHP 8.0.x.

And I installed/added ContentEditor plugin via the back-end plugin administration front-end.

**Comment by tleonard2** [comment]
I had moved my site to Bootstrap 5 which does not rely on jquery and so it was not installed. Once I installed jquery, the editor started working. thanks for your help narrowing things down.

**Comment by arvislacis** [comment]
@tleonard2 Nice to know that. Maybe you didn't include `{% framework %}` or `{% framework extras %}` in your initial theme, layout which automatically adds jQuery from Winter CMS back-end and also is needed for Ajax related functionality.

Anyways, I glad that you have solved this problem. :)
