### ISSUE TITLE
button stuck at spinning gear animation prevents using the plugin

### ISSUE THREAD

**Issue by DPTOProgramacionIslaNetworks** [Samuell1/contenteditor-plugin#118]
hi, i just installed the latest version of this plugin, in octobercms v2
after i click the edit icon
![image](https://user-images.githubusercontent.com/90899429/176391158-867eb17b-eaa7-4e4d-9cee-3173a92fd53a.png)
the button changes to a spinning gear icon and does not get past that 
![image](https://user-images.githubusercontent.com/90899429/176391319-01263f98-cf58-45e3-a2c7-16c038ca88a7.png)
i have the following errors on chrome dev console
![image](https://user-images.githubusercontent.com/90899429/176391422-621eb30a-17fc-4254-9df6-c6f2c97712cc.png)
![image](https://user-images.githubusercontent.com/90899429/176391905-ef60f0d6-ee02-4112-9acd-ef7f5e5d70de.png)

**Comment by samuelpatro** [comment]
Hey, this looks like you forgot to name something or issue with jquery?

**Comment by Pixinside** [comment]
I had the same issue. You might try to add the filename to the tag (for ex):
`{% component 'contenteditor' file="homel.htm" %} `
