### ISSUE TITLE
How to use style palettes?

### ISSUE THREAD

**Issue by andrewfenn** [Samuell1/contenteditor-plugin#12]
I can see an option to define custom style palettes. I don't understand though what do to make them correctly enable/disable the options available in the editable content areas.

**Comment by samuelpatro** [comment]
Hey, in bottom left corner you can open settings for tag and first tab you can select yours patterns.

**Comment by CptMeatball** [comment]
Maybe it's an idea to link to the docs of ContentEditor itself in the ReadMe?

**Comment by andrewfenn** [comment]
ok. I see it. Thanks.

**Comment by andrewfenn** [comment]
Could you point me to the docs you're referring to.

I am interested in adding my own tags on top of your plugin, for example a more complicated image upload tag, any documentation you could point me at would be appreciated.

**Comment by CptMeatball** [comment]
I meant ContentTools instead of ContentEditor. My bad. 

I referred to http://getcontenttools.com
