### ISSUE TITLE
Way to custom filter tags via attribute or some kind of ID

### ISSUE THREAD

**Issue by andrewfenn** [Samuell1/contenteditor-plugin#13]
I would like to make the feature request to be able to lock down what can be edited in a certain space via the attributes.

For example say I have the following
` {% component 'contenteditor' file="welcome.htm" %}`

I want to be able to lock it down to only allow p or img tags like so..
`{% component 'contenteditor' file="welcome.htm" allow_only="p,img" %}`

When a user clicks to edit the content only the p and img tags.

At first I thought this is what Style Palettes were for. So perhaps it's better done in such a way in which you make a list similar to the where you add Style Palettes and then you just give it a name like so...
`{% component 'contenteditor' file="welcome.htm" allow_only="example_name" %}`

**Comment by samuelpatro** [comment]
I can add filtering by not tag but Tools, what tools you need to show for specific content

**Comment by samuelpatro** [comment]
@andrewfenn i added `tools` property in latest update! You can define what tools you need for specific content
