### ISSUE TITLE
An attribute value for changing the media upload directory depending upon editable content area or page

### ISSUE THREAD

**Issue by andrewfenn** [Samuell1/contenteditor-plugin#14]
It would be nice to be able to define multiple upload locations so that when users upload assets to certain content areas or pages things will be automatically organised into different paths as opposed to having a global setting where everything is placed.

For example maybe something like this..

`{% component 'contenteditor' file="welcome.htm" image_folder="/examplefolder/" %}`

**Comment by CptMeatball** [comment]
Not sure what you mean by this. What is the "global setting" you refer to?

**Comment by andrewfenn** [comment]
I mean the "Images folder name".

![screenshot from 2017-02-17 08-54-19](https://cloud.githubusercontent.com/assets/409265/23049441/b361e0fc-f4ee-11e6-88f8-0e19844b6d7a.png)

**Comment by samuelpatro** [comment]
And then images will be uploaded to `somefolder/examplefolder/` ? or only to examplefolder?

**Comment by andrewfenn** [comment]
My original intention was only to /examplefolder however either way works for me as long as there is a way to be able to split up uploaded content so that it's not all just in one folder as I can imagine it getting very messy.

**Comment by samuelpatro** [comment]
@andrewfenn i trying to do it but i cant find i way how to send a folder name to imageuploader :/
