### ISSUE TITLE
Use october way to create image path

### ISSUE THREAD

**Issue by ghost** [Samuell1/contenteditor-plugin#15]
Hello,

Really nice plugin.

However, I discovered that it use absolute url to create image path. It would be better to use the october syntax

    <img src="{{ '/folderpath/dummy.png'|media }} alt="Dummy image" />

do you think it's possible ? Can it be planned ?

Regards,

Alex

**Comment by CptMeatball** [comment]
What would be the direct advantage of this change? You can see the image in the media folder, but you can't do anything with it without breaking the front-end (apart from overwriting it).

**Comment by ghost** [comment]
The benefit is that's a better practice for the october CMS as it's the recommanded way to get the image path. For example if, for some reason, you have to change the path of your media directory, you don't need to change the "src" attributes of all your images, instead, you work on the media variable of october CMS.

In addition, it can prepare the images to be extended, for example with the [image resizer plugin](https://octobercms.com/plugin/toughdeveloper-imageresizer) that works as a twif filter. If the contenteditor plugin can't understand mustache tags, that possibility can be forget definitively.

So I think there are plenty advantages to use october syntax for images.

**Comment by samuelpatro** [comment]
I think, it can be possible but image cant be rendered because, that media tag needs to be parsed with php not js, you can see only empty image without nothing

**Comment by ghost** [comment]
Maybe the contenteditor plugin can globally register the path of october media tag and make it available in javascript.

The same way you define the contenteditor default media folder in backend, that variable is not registered in JS, but it can be accessed by contenteditor js plugin when it need to upload an image.

**Comment by samuelpatro** [comment]
Register default media folder is something other then this. `{{ '/folderpath/dummy.png'|media }}` this needs to be parsed with php template system TWIG, but you cant parse php on frontend

**Comment by CptMeatball** [comment]
The Media Manager isn't accessible on the front-end (AFAIK), so there is no clean way to implement this feature I think.
