### ISSUE TITLE
Javascript issue when attempting to save on front end

### ISSUE THREAD

**Issue by andrewfenn** [Samuell1/contenteditor-plugin#17]
Recently started getting the following error...

![js errors](https://cloud.githubusercontent.com/assets/409265/24642192/b5b2f6d8-192f-11e7-9f92-811f9c48167f.png)

![error](https://cloud.githubusercontent.com/assets/409265/24642198/bb49f24a-192f-11e7-9aa4-906fba6240bb.png)

I deleted and re-installed the plugin, but it's the same result. Theme and content is the Demo Theme/Content from the October default install.

Plugin version: 1.0.4
October Demo: 1.0.1

**Comment by samuelpatro** [comment]
Do you have `{% framework %}` in layout?

**Comment by samuelpatro** [comment]
@andrewfenn any news on this?

**Comment by CptMeatball** [comment]
I'm guessing he fixed it by adding framework tags.

**Comment by andrewfenn** [comment]
Sorry guys, i forgot about this and went on holiday, I'm guessing you're right it might be that, I'll close this until i have time to look into it again.
