### ISSUE TITLE
it doesn't seem to create a new file for a translation

### ISSUE THREAD

**Issue by aurukas** [Samuell1/contenteditor-plugin#19]
it doesn't seem to create a new file for a translation. I switch the locale, then save. But nothing is created. The original file is rewritten instead. Am I doing something wrong?

**Comment by samuelpatro** [comment]
Hey, do you try refresh website after changing translation? What is name for that file? name.en.htm?

**Comment by aurukas** [comment]
yes, I do refresh. My default filename is without a locale prefix. Should I add one?

**Comment by aurukas** [comment]
i've tried adding a locale suffix to my default filename. Now it has created another file, but without the appropriate suffix...

**Comment by samuelpatro** [comment]
@aurukas oh :( it is weird, i can look at it

**Comment by samuelpatro** [comment]
@aurukas i found it! thanks for reporting it

**Comment by aurukas** [comment]
no sweat. Thank YOU

**Comment by samuelpatro** [comment]
Its fixed in 1.0.6!
