### ISSUE TITLE
Great plugin

### ISSUE THREAD

**Issue by kferran** [Samuell1/contenteditor-plugin#2]
Hey man, great job with this plugin! 

Currently I have a copy of the dev branch running on a site we are working on. Do you have a list of items you are currently working on for this next release? Anything you could use some help with?

**Comment by samuelpatro** [comment]
Hi, thanks!

This features are in 1.0.3 (dev) but i waiting for fix taglist bug in octoberCMS

Image upload to MediaLibrary (v1.0.3)
Settings in backend (v1.0.3)
Autocreate file if not exists (v1.0.3)
