### ISSUE TITLE
Not saving

### ISSUE THREAD

**Issue by leohner** [Samuell1/contenteditor-plugin#22]
I get the editor working and everything seems to be working smoothly, but when I go to save, the gear icon just spins indefinitely. 

Any help would be greatly appreciated!

Thanks!

**Comment by samuelpatro** [comment]
Hey, can you please provide errors from console and versions of octobercms and other plugins?

**Comment by leohner** [comment]
Okay, my fault. I had the slim version of jquery running when I needed the full version for ajax. Sorry about that. Thanks for making an awesome plugin! You're the best!
