### ISSUE TITLE
No File Name Error

### ISSUE THREAD

**Issue by leohner** [Samuell1/contenteditor-plugin#25]
In the documents, I can't determine if a blank file name is acceptable. 

But when trying to save a page with no file name listed, I get an error saying ".en is not a valid extension." The plugin injects the .en automatically and causes it to fail.

When declaring a file name, this error doesn't appear.
Wanted to clarify this issue and ensure it's not a bug, and if it is that it can be fixed.

Thanks! And I really appreciate all of your hard work!

**Comment by samuelpatro** [comment]
Hey, thanks for report but you need to still set file name because for autocreating

**Comment by leohner** [comment]
Ah, okay! Thank you!

**Comment by samuelpatro** [comment]
No problem, because there is function what is finding if exists or not and then autocreate new file :)

**Comment by colthreepv** [comment]
watch out, [this commit changes the aforementioned behaviour](https://github.com/Samuell1/contenteditor/commit/d39ae60c08da66093a3dcb85fcb007e7ee3653b8)
