### ISSUE TITLE
Table editing problems

### ISSUE THREAD

**Issue by vdomah** [Samuell1/contenteditor-plugin#27]
It's confusing how table editing works. I was looking how to add a table if my content already got one. Found that I need first create a P element and then add table from it. Then if I add another row in that new table I don't have a way to remove this table.
You can check this on my test site: http://gek.dp.ua/custom/stockist
Admin access to enable content editor on front: http://gek.dp.ua/custom/backend test / 111111

**Comment by samuelpatro** [comment]
Hey, can you create image(gif) for it?
