### ISSUE TITLE
Component properties polluting next instance

### ISSUE THREAD

**Issue by colthreepv** [Samuell1/contenteditor-plugin#29]
My pages look like that:

```twig
title = "great page"
url = "/myurl"
[contenteditor]
==
<section>
  {% component 'contenteditor' file='00-content.htm' fixture='p' %}
</section>
<footer>
  {% component 'contenteditor' file='05-footer.htm' %}
</footer>
```

An annoying thing happens: on the second contenteditor instance, the component reads `$this->property('fixture') = 'p'`, and not undefined (as it should)

This is probably because of the component re-use, in theory there should be N component instances on page top (using aliases) for each component invocation inside the page.
In theory everything is fine, but in practice it's very repetitive.

Could we devise a workaround?

**Comment by samuelpatro** [comment]
Hey, i think its because there is not fixture property on next component then it will reuse from first, i think this is bug.

**Comment by colthreepv** [comment]
Yes, I am trying to fix this one by having 2 components: `contenteditor` and `texteditor`.

Texteditor will work flawlessly when only the text, and not the style has to be edited, and it will not pollute contenteditor with properties. [You can check it out here](https://github.com/colthreepv/contenteditor/tree/develop)

I am not sure which other use-cases there are for the `fixtures` property.

**Comment by colthreepv** [comment]
any update on this and PR #30 ?

**Comment by samuelpatro** [comment]
Hey, i merged it to develop, but i need to test it all, there soo many new things :) But next version will have this new things and many of them are from pull requests :)

- Added compatibility with StaticPages #20
- Fix empty content file #23
- Show settings tools as default && If no translation file - use default #26 
- Added data-ce-tag to treat a fixture as text #30 
- Updated Content Editor to 1.3.2 #30

**Comment by colthreepv** [comment]
sure, thanks for the feedback, I pinged back to keep the discussion alive.

Regarding the current issue (#29), I have "fixed" it in my fork using 2 specific components, as suggested on the previous comment, but it radically changes the plugin functionality, so I am not sure about a PR.

**Comment by samuelpatro** [comment]
I think fix for this issue can be fixed by using default value for properties like is used in `tools`or `file`

**Comment by samuelpatro** [comment]
I think i fixed this in developed branch.
