### ISSUE TITLE
Error when adding a new item in the Style palet

### ISSUE THREAD

**Issue by ghost** [Samuell1/contenteditor-plugin#3]
Hello,

I downloaded the test dev version. When I go to settings > Content Editor Settings > Style palette and I click on "Add new item", I get an error in a popup :

> "array_merge(): Argument #1 is not an array" on line 2 of /modules/backend/formwidgets/taglist/partials/_taglist.htm

Any ideas to fix that ?

Thanks

Alex

**Comment by samuelpatro** [comment]
I can't fix it, this issue is inside october "taglist"
https://github.com/octobercms/october/issues/2254

**Comment by ghost** [comment]
Ok thank you for your answer. How did you handle the problem ? (I see that in the plugin screenshot, you defined some styles).

**Comment by samuelpatro** [comment]
I edit octoberCMS file (_taglist.htm), in that issue is how to solve that
