### ISSUE TITLE
Using contenteditor component inside partial doesn't register onSave on page

### ISSUE THREAD

**Issue by colthreepv** [Samuell1/contenteditor-plugin#31]
Hi (again), I found your plugin very useful for my project, before posting the issue I would thank you again for that.

I have noticed that using the component inside a partial page like

`partials/navbar.htm`
```
[contenteditor]
==
<nav>
  {% component 'contenteditor' file='partial-navbar/content.htm' %}'
</nav>
```

After editing the content and trying to save, the page answers with a 500 telling that `contenteditor::onSave` is not defined.

A workaround to that is to add `[contenteditor]` also on the page including the partial.

Can this be fixed? I don't have such an extensive knowledge of php/october

**Comment by samuelpatro** [comment]
Hi, yes you need to have component on page. But i can look at it maybe i find some workaround.

**Comment by ghost** [comment]
I'm not sure you will be able to make it works on partial as partial can't deal with ajax stuff.

**Comment by samuelpatro** [comment]
I think @Alex360hd is true https://octobercms.com/docs/cms/partials#life-cycle-limitations
