### ISSUE TITLE
Not working inside subdirectory

### ISSUE THREAD

**Issue by tamipangadil** [Samuell1/contenteditor-plugin#33]
I just want to report some minor bugs but it shouldn't be ignored.

So, I have OctoberCMS installed inside my directory and excited to use your plugin.

I've encountered that I'm not able to upload media. So, I checked your JS code then noticed that you are using relative path when doing AJAX call.

`Line 200: xhr.open('POST', '/samuell/contenteditor/image/upload', true);`

`Line 261: xhr.open('POST', '/samuell/contenteditor/image/save', true);`

It would be better if you are able to get the base url installation path of the site.

**Comment by samuelpatro** [comment]
Fixed in https://github.com/Samuell1/contenteditor/commit/e7d6f69720b43045f2d191fa9de518d5076a7c0a

**Comment by tamipangadil** [comment]
I didn't notice that I forgot to respond to your comment.

Thanks for the fix. I have used it already after your updates.
