### ISSUE TITLE
Repeating Styles

### ISSUE THREAD

**Issue by leohner** [Samuell1/contenteditor-plugin#34]
I don't know why this is happening, but the styles for the content editor are repeating four times. All of the same-titled styles are linked (turning one off turns them all off). 

Any insight would be helpful. 

Thank you!

![content-styles](https://user-images.githubusercontent.com/17093330/29487388-20b1ee1a-84c6-11e7-8089-8c9859c9dcd8.png)
![multiplying-styles](https://user-images.githubusercontent.com/17093330/29487389-20b3fc78-84c6-11e7-9cdd-3e63ca4b746f.png)

**Comment by samuelpatro** [comment]
Hey, thanks for issue! Do you have more then 1 contenteditor component?

**Comment by leohner** [comment]
Thanks for the prompt reply! I do have more than one editor component, but they're all being referenced by the same component, like {% component "contenteditor" file="file1.htm" %} and {% component "contenteditor" file="file2.htm" %}. 

I did have multiple instances, ie:  contenteditor, contenteditor2, etc. Getting rid of those and having one component didn't make a difference though.

**Comment by samuelpatro** [comment]
I think i know where is problem: every new component is adding new code and that code is attaching to all components :(

Thanks for reporting this issue, i look at it in this week.

**Comment by leohner** [comment]
You're the best! Thanks!

**Comment by samuelpatro** [comment]
@fuchsli Hey, i fixed it in develop branch https://github.com/Samuell1/contenteditor/commit/e41128fff6883b41a5b359ade83ceb110110ff63

**Comment by leohner** [comment]
Thank you so much!

I hate to note another bug with this, but it seems the auto-create file functionality has been lost because of this. The Error Page gets shown when I try to do it without first creating the content file. 

Definitely not the end of the world and is certainly manageable. 

I appreciate everything you do to make October so wonderful. It's far and away the best CMS I've ever used.

**Comment by samuelpatro** [comment]
Thanks for response, can you please paste that error code here? There was small refactoring maybe something is bad

**Comment by leohner** [comment]
I'm not sure which part to copy, so here's a sampling: 

Type: Twig Template
Exception: Cms\Classes\CmsException

`An exception has been thrown during the rendering of a template ("The content file 'homepage/test-to-break.htm' is not found.").`

`#	CALLED CODE	DOCUMENT	LINE
48	Twig_Template->displayWithErrorHandling(…)	~/vendor/twig/twig/lib/Twig/Template.php	403
47	Twig_Template->display(…)	~/vendor/twig/twig/lib/Twig/Template.php	411
46	Twig_Template->render(…)	~/modules/cms/classes/Controller.php	376
45	Cms\Classes\Controller->runPage(…)	~/modules/cms/classes/Controller.php	213
44	Cms\Classes\Controller->run(…)	~/modules/cms/classes/CmsController.php	50
43	Cms\Classes\CmsController->run(…)		
42	call_user_func_array(…)	~/vendor/laravel/framework/src/Illuminate/Routing/Controller.php	256
41	Illuminate\Routing\Controller->callAction(…)	~/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php	164
40	Illuminate\Routing\ControllerDispatcher->call(…)	~/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php	112
39	Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(…)		
38	call_user_func(…)	~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php	139
37	Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…)		
36	call_user_func(…)	~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php	102
35	Illuminate\Pipeline\Pipeline->then(…)	~/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php	114
34	Illuminate\Routing\ControllerDispatcher->callWithinStack(…)	~/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php	68
33	Illuminate\Routing\ControllerDispatcher->dispatch(…)	~/vendor/laravel/framework/src/Illuminate/Routing/Route.php	203
32	Illuminate\Routing\Route->runWithCustomDispatcher(…)	~/vendor/laravel/framework/src/Illuminate/Routing/Route.php	134
31	Illuminate\Routing\Route->run(…)	~/vendor/laravel/framework/src/Illuminate/Routing/Router.php	708
30	Illuminate\Routing\Router->Illuminate\Routing\{closure}(…)		
29	call_user_func(…)	~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php	139
28	Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…)		
27	call_user_func(…)	~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php	102
26	Illuminate\Pipeline\Pipeline->then(…)	~/vendor/laravel/framework/src/Illuminate/Routing/Router.php	710
25	Illuminate\Routing\Router->runRouteWithinStack(…)	~/vendor/laravel/framework/src/Illuminate/Routing/Router.php	674
24	Illuminate\Routing\Router->dispatchToRoute(…)	~/vendor/laravel/framework/src/Illuminate/Routing/Router.php	635
23	Illuminate\Routing\Router->dispatch(…)	~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php	236
22	Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(…)		
21	call_user_func(…)	~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php	139
20	Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…)	~/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php	49
19	Illuminate\View\Middleware\ShareErrorsFromSession->handle(…)		
18	call_user_func_array(…)	~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php	124
17	Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…)	~/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php	62
16	Illuminate\Session\Middleware\StartSession->handle(…)		
15	call_user_func_array(…)	~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php	124
14	Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…)	~/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php	37
13	Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(…)		
12	call_user_func_array(…)	~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php	124
11	Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…)	~/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php	59
10	Illuminate\Cookie\Middleware\EncryptCookies->handle(…)		
9	call_user_func_array(…)	~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php	124
8	Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…)	~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php	44
7	Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(…)		
6	call_user_func_array(…)	~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php	124
5	Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…)		
4	call_user_func(…)	~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php	102
3	Illuminate\Pipeline\Pipeline->then(…)	~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php	122
2	Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(…)	~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php	87
1	Illuminate\Foundation\Http\Kernel->handle(…)	~/index.php	43`
