### ISSUE TITLE
Headings not showing in my Tools list

### ISSUE THREAD

**Issue by stefanreimert** [Samuell1/contenteditor-plugin#35]
* `heading`        => Heading (h1)
* `subheading`     => Subheading (h2)
* `subheading3`    => Subheading3 (h3)
* `subheading4`    => Subheading4 (h4)
* `subheading5`    => Subheading5 (h5)

I only get to see Heading one en subheading 2.
What i need to have is the h3,h4,h5,h6.

I see the headings but when i select the content text the h3,h4,h5,h6 disappear.
If you need more information let me know.

**Comment by samuelpatro** [comment]
Hey, do you using fixture? And what version of content editor do you using?

**Comment by stefanreimert** [comment]
Hello, I just picked up the latest version from the dev repo.

**Comment by stefanreimert** [comment]
![schermafbeelding 2017-08-21 om 11 00 26](https://user-images.githubusercontent.com/4490250/29511649-04c660e6-8660-11e7-953a-44e12d201d30.png)
![schermafbeelding 2017-08-21 om 11 00 38](https://user-images.githubusercontent.com/4490250/29511650-04cb919c-8660-11e7-8452-7fbe2869bd38.png)

This only happens the first time i click the edit button.
Then it stays without the h3,h4,h5.

**Comment by stefanreimert** [comment]
Sorry this whas my fault it is working. Misplased the *

**Comment by stefanreimert** [comment]
Ok now i see when i remove the * i can select all the headers.
But doesnt it needs to be that i add the *?

**Comment by samuelpatro** [comment]
`tools="*"` is for all default in content editor not yours defined
