### ISSUE TITLE
Separate component instances on page override each other's fixture

### ISSUE THREAD

**Issue by vdomah** [Samuell1/contenteditor-plugin#41]
If I call
{% component 'contenteditor' file="home-title.htm" fixture="h2" %}

and after that I want to paste another instance without fixture I need to specify empty fixture, otherwise the fixture from the previous call will be used.
{% component 'contenteditor' file="home-subtitle.htm" fixture="" %}

**Comment by samuelpatro** [comment]
What version do you using?

**Comment by Gohanova** [comment]
i am having the same Issue - and i was wondering: do i need to set up a new instance of this Component for every block i need to be editable?

Meaning,  can i use one instance multiple times:

{% component 'contenteditor' file="title.htm"  %}
{% component 'contenteditor' file="text.htm"  %}
{% component 'contenteditor' file="list.htm"  %}
{% component 'contenteditor' file="moreText.htm"  %}
(are there any risks involved - doing it like this: is there a chance that the Editor will mix-up connection the the Content, or some other problems)

or do i need to give each instance a unique name?

{% component 'editor_1' file="title.htm"  %}
{% component 'editor_2'' file="text.htm"  %}
{% component 'editor_3'' file="list.htm"  %}

By the way - great Plugin! Thanks for providing!!

**Comment by samuelpatro** [comment]
@Gohanova hey, you doesnt need to make new instances of component, use only one.

**Comment by Gohanova** [comment]
great - thx for your quick replay
one Tip: there is a dead Link on your "October CMS - plugin-page":

"List of planned features you can find **here**."

https://octobercms.com/plugin/samuell-contenteditor

<img width="665" alt="bildschirmfoto 2017-11-10 um 16 57 36" src="https://user-images.githubusercontent.com/32397825/32666658-7a537336-c638-11e7-9311-ccc4582db08f.png">

**Comment by Zmove** [comment]
Can confirm the original issue. If you have one call to contenteditor with a fixture, all the following call will share that same fixture. The only way to not have this behavior is to manually specify an empty fixture to all elements, which is a little annoying.

Don't know why this issue has been closed, do I have to create a new one ?

Can confirm the bug on a fresh october and plugin install. (so latest versions from yesteday)
