### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by Gohanova** [Samuell1/contenteditor-plugin#43]
Hi,
I have a suggestion for a future enhancement:
i would like to use this plugin, without giving my client access to the CMS section.
I fear, he might messup the code. Thats why i installed this plugin.

Maybe it is possible, to integrate this plugin in the administrator-permission:

Settings > Administrators > Permissions

Thanks for this plugin! Its a great addition to October CMS!

**Comment by samuelpatro** [comment]
Hey, simply put only for client `content_manager` permissions.

**Comment by Gohanova** [comment]
thx for your feedback!
