### ISSUE TITLE
multiple inline fields on a page?

### ISSUE THREAD

**Issue by stacksavings** [Samuell1/contenteditor-plugin#44]
I don't understand how this is supposed to work for inline fields, are we supposed to make a new content page for each inline field? From the documentation, it seems that fixtures are supposed to support this, so we can set a fixture id for each inline field and, presumably, it would read from the same file. This does not seem to be the case at all. Without support for making many different fields on the page editable I am failing to see the usefulness of a plugin like this. Am I misunderstanding how to use this?

**Comment by samuelpatro** [comment]
Yes, now iam limited by content files but i want to make other component that can save code, texts... to database that will be simple and better to maintain shorter texts
