### ISSUE TITLE
checkEditor() return null

### ISSUE THREAD

**Issue by patosG** [Samuell1/contenteditor-plugin#45]
BackendAuth::getUser() return null in route.php even the user is logged.
I gues due to something similar than here https://github.com/octobercms/october/issues/3052
PHP 7.1 - last october version

**Comment by shiftaltd** [comment]
PHP7.0 Last october version

**Comment by samuelpatro** [comment]
Fixed https://github.com/Samuell1/contenteditor/commit/6e0a72dbf5728de2582e711d9018c8c0edcd4294
