### ISSUE TITLE
I can't manage to get the plugin working

### ISSUE THREAD

**Issue by Gudmundsdottir** [Samuell1/contenteditor-plugin#46]
Hi Samuell,
I've installed the plugin and I've put {% component 'contenteditor' file="info.htm" %} tag in my home page. Then I've created info.htm in contents. I've also added {% framework extras %}, {% scripts %} and {% styles %} (last one in the head section), but nothing happens when I'm in the front end.
I'm logged as developer and I'm using a local installation with XAMPP.

What am I doing wrong? Thanks in advance!

**Comment by samuelpatro** [comment]
Hey,

Do you have content editor component in your page?

**Comment by Gudmundsdottir** [comment]
No... :P 
That's the thing I've been missing! Thank you, now it works!

(I'm sorry, I'm new to October)

**Comment by Antar74** [comment]
Hello Samuell
Im' having the same issue, I do not see the pencil in the front end and cannot edit the content block (although the content do show). I double checked the tags (scripts, framework extras and styles) and are all on place plus I added the component to the page. 

And I see that for each content to be editable I have to add a component? I have aproximately 10 content blocks on a single page and would like all to be editable... is that [possible?
