### ISSUE TITLE
Setup Tutorial

### ISSUE THREAD

**Issue by daslicht** [Samuell1/contenteditor-plugin#49]
Hi,
I have craeted a statioc page.

When I now add (drag) the component to a cms page i can select the static page from the dropdown of the component.

![](https://i.imgur.com/qWxvIOF.png)

![](https://i.imgur.com/lhEFTGL.png)

My layout contains: 

```
    {% framework extras %}
    {% scripts %}
```

But when I navigate to my homepage I dont get the editor Icon displayed?

What else is missing please?

**Comment by samuelpatro** [comment]
Hey, do you have jquery on website? And dont forget `{% styles %}`

**Comment by daslicht** [comment]
yeah I have jQuery and Styles in there:

http://october.ansolas.de

**Comment by samuelpatro** [comment]
Do you get any errors in console?

**Comment by daslicht** [comment]
No errors in console , is the setup in my picture correct ?

**Comment by samuelpatro** [comment]
If you try using only `content` files? It works?

**Comment by daslicht** [comment]
Looks like I do not have teh full overview yet. Isnt my 'home' a content file ?
like to have a look in my october ?

**Comment by samuelpatro** [comment]
Yes but you need to use  **CMS > Content** files from october not from **Pages plugin**

**Comment by daslicht** [comment]
Got it wokring after reducing anything to the barebones , now I find my way !
Thank you !

**Comment by daslicht** [comment]
yikes, saving thows the following error:

![](https://i.imgur.com/ID1xsoz.png)

**Comment by daslicht** [comment]
got it, framework EXTRAS is needed and not just framework
