### ISSUE TITLE
In place editing for rainlab blog ?

### ISSUE THREAD

**Issue by daslicht** [Samuell1/contenteditor-plugin#50]
Is it possible to edit blog posts as well ?

**Comment by samuelpatro** [comment]
Now iam not sure if can be possible because rainlab blog plugin is using markdown not html as content of blog.

**Comment by amdad** [comment]
Ok, ignore Markdown. What if plugin like exactly like  rainlab.blog use HTML editor?

**Comment by samuelpatro** [comment]
It can be possible but separately integrating Content Tools library not Content Editor plugin.
