### ISSUE TITLE
Error: Dynamic page link edit Problem 

### ISSUE THREAD

**Issue by mitulkoradiya** [Samuell1/contenteditor-plugin#51]
Hello,

How to make dynamic page link editable using content editor.
content html file : 
`<p><a href="bedroom'|page">El confort.</a></p> `

 
![11](https://user-images.githubusercontent.com/13043276/37887168-ee4134a8-30dd-11e8-855b-4862381d1707.png)

How to make editable this link or only edit the link text?

Thanks.

**Comment by samuelpatro** [comment]
Sorry but i cant find a way to how to support twig tags in content files.
