### ISSUE TITLE
Unable to upload images

### ISSUE THREAD

**Issue by wertykid** [Samuell1/contenteditor-plugin#52]
Hello, I was trying to add some images but it always gives me an error and I cannot upload the image.
Here is the error:
![error](https://user-images.githubusercontent.com/15935795/38163518-b8836950-3527-11e8-89f7-3428bd252688.PNG)

In addition to that, can I know how I can add CSS to change text colour for the content added using this plugin? Thank you very much.

**Comment by samuelpatro** [comment]
Hey, can you please check console is there is error?
