### ISSUE TITLE
All tools (*) show no tool

### ISSUE THREAD

**Issue by daslicht** [Samuell1/contenteditor-plugin#54]
Hi,
when i setup the component like this : 

![](https://i.imgur.com/6p6DoOl.png)
i get : 
![](https://i.imgur.com/9Nm6kTY.png)

When I do not add any parameter I get :
![](https://i.imgur.com/6C9o9qS.png)

But how to use the disbled tool's ? 
I tried setting the focus at several places but they always stay disabled?
What do I miss? please.

**Comment by samuelpatro** [comment]
They are disabled because there is nothing inside your content.

**Comment by daslicht** [comment]
![](https://i.imgur.com/J1yvZo5.png)
there is content ...

**Comment by samuelpatro** [comment]
Try selecting and they should be enabled. This is nothing to do with Content Editor, its mostly on Content Tools side.

**Comment by daslicht** [comment]
when I select something I get : 

![](https://i.imgur.com/j6bT05l.png) :/

same when create a new paragraph by hitting enter

**Comment by samuelpatro** [comment]
Do you edited something in js files? Do you get errors in console?

**Comment by daslicht** [comment]
nope no errors , nothing edited, the other fubnctions like BOLD works perfectly

**Comment by samuelpatro** [comment]
Can you test it on empty page? without any additional css,js?

**Comment by daslicht** [comment]
I will do, but that will take some time

**Comment by samuelpatro** [comment]
Just make new layout (with scripts, styles needed for contenteditor) and make empty page :)

**Comment by daslicht** [comment]
it works on an empty page .

I found teh error, I added a string to the component parameter :``` Content block tag with disabled toolbox```

after removing it, any tool is working, except indent
