### ISSUE TITLE
It only works with "p" and "h" tags?

### ISSUE THREAD

**Issue by Antar74** [Samuell1/contenteditor-plugin#56]
Hello... I'm using your awesome plugin to make frontend content editable. Congrats for such great work! :)

I'm having a problem, I'm trying to make a menu editable (a "ul" tag with "li" tags all with css classes) here is the code:

`
        <ul class="nav flex-column lfm-border pt-3 fixedsticky text-uppercase">`
            `<li class="nav-item">`
               ` <a class="nav-link smooth-scroll" href="#inicial">BCD Educación Inicial</a>`
           ` </li>`
           ` <li class="nav-item">`
               ` <a class="nav-link smooth-scroll" href="#primaria">BCD Primaria</a>`
            `</li>`
           ` <li class="nav-item">`
                `<a class="nav-link smooth-scroll" href="#secundaria">CDI Secundaria</a>`
         `   </li>`
        `</ul>`

I see the menu rendered but if I try to edit by clicking the green tick I only get three dots and the whole "ul" structure remains untouched. 

I see that when the content is between "p" tags or "h" tags I can edit and access the code by clicking the tag down below to the left on the page (in what appears to be a tag selector). 

Any ideas how can I use your plugin to make a menu editable on the front end?

Thanx!

**Comment by samuelpatro** [comment]
Hey, you can try using a fixture to make a element as a UL maybe it helps.
