### ISSUE TITLE
In editing mode, images come out of their flow and overlap other content

### ISSUE THREAD

**Issue by Bensji** [Samuell1/contenteditor-plugin#59]
Hi,

Great plugin. Although I have an issue with using (bigger) images.
If I let them fill the container (so they are displayed smaller than then are) and I go to editing mode, the images come out of their flow and overlap other content, ...

They do go back to their regular flow after saving though.

This happens because of the images displaying as background-images, and using the dimensions of the image itself, how can I fix this (I located the code to the minified JS file, but I'm kinda hesitant to change anything in there).

Thank you in advance

**Comment by samuelpatro** [comment]
Hey, best will be to use it as img tag.
