### ISSUE TITLE
Plugin is not working for me

### ISSUE THREAD

**Issue by iSaadSalman** [Samuell1/contenteditor-plugin#6]
I did the following and it does not seem to work for me: 

1. Installed the plugin via October Installer
2. Added the {% styles %}   {% framework extras %} {% scripts %} into my layout file
3. Set the "Menage website content file" to allow.
4. Added {% component 'contenteditor' file="test.htm" %} into my page with appropriate content "test.htm" created.

Still does not work for me :( I checked the html and content-tools.min.js is not loaded

**Comment by samuelpatro** [comment]
Hey, thanks for feedback, can you please provide more info about october? (version, what plugins you use.. etc)

Btw you have component for page added?
![obrazok](https://cloud.githubusercontent.com/assets/3110002/20924920/22a8e506-bbb4-11e6-8814-e2bae0919d3c.png)

**Comment by iSaadSalman** [comment]
It works after drag the component in the page. Is this a requirement?

**Comment by samuelpatro** [comment]
Its required, because you calling component 

First step is: Drop the Content Editor component to a CMS page.
