### ISSUE TITLE
Allow multiple css classes for custom style pallete

### ISSUE THREAD

**Issue by angay9** [Samuell1/contenteditor-plugin#62]
Hi,
thanks for great plugin.

Could you please allow to add multiple css class names in a user defined style palette.
Right now If I add 2 classes like 'heading heading-outlined', and then try to apply this style in the frontend, I get the error saying 
```
Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('heading heading-outlined') contains HTML space characters, which are not valid in tokens.
```

If you could please fix this issue it would be great, thanks.

**Comment by samuelpatro** [comment]
Hey, this cant be fixed because its DOM error. You can just separate your css classes to one more class like `heading` and other `heading-outlined`
