### ISSUE TITLE
Component doesn't work in partials

### ISSUE THREAD

**Issue by carcade** [Samuell1/contenteditor-plugin#64]
Thanks for such a great plugin!

It works in pages and layouts, but if I place component inside partial - it doesn't work (outputs ajax error).
BUT if i put component in layout, and place `{% component ... %}` code in child partial - it works.

Could you please check it and fix?

**Comment by Samuell1** [comment]
This cant be fixed because partials doesnt not support components.

**Comment by samuelpatro** [comment]
http://octobercms.com/docs/cms/partials#life-cycle-limitations
