### ISSUE TITLE
Plugin image uploads does not work for OctoberCMS installations not in root folder.

### ISSUE THREAD

**Issue by thesigae** [Samuell1/contenteditor-plugin#67]
I noticed while developing with your plugin that the image upload won't post when the OctoberCMS site is not installed in the `/` directory.

This is my development environment:
`http://localhost:8080/october/delta`

When I try to make a post it wants to post to:

`http://localhost:8080/samuell/contenteditor/image/upload`

![image](https://user-images.githubusercontent.com/20378254/45710783-75960d00-bb3c-11e8-9885-22f6776083fb.png)

It should be /october/samuell

`http://localhost:8080/october/samuell/contenteditor/image/upload`

**Comment by samuelpatro** [comment]
Hey, maybe this is issue with getting location url that i passing here: 

https://github.com/Samuell1/contenteditor/blob/0441bbd6ba20a3091eb26fd9a0ea06a73263f28e/assets/contenteditor.js#L7

Can you log it in browser console what url you get?

**Comment by thesigae** [comment]
This is what the log shows for the site origin: 

![image](https://user-images.githubusercontent.com/20378254/45839767-241b8880-bcca-11e8-9cd3-e65f719120fe.png)

I changed the variable to this and it worked.

`var siteUrl = 'http://localhost:8080/october/'; // get site url for requests`

Also I noticed that the crop button works but the rotate image buttons do not work. It tells me nothing in the console when I push the rotate 90 deg buttons.

**Comment by samuelpatro** [comment]
Then yeah thats the issue because, document.location dont know if its website hosted in folder or not but for now its good to change that path by self or use vhosts on your OS to refer to this folder as domain.

Crop buttons doesnt work because there is not implemented a crop backend for it.

**Comment by thesigae** [comment]
The best approach to fix this is to add a setting in the the plugins backend setting where you can specify the directory of the October installation. Basically do a an if statement:

`if (url_from_backend) {
    var siteUrl = url_from_backend; // get site url for requests
} else { 
    var siteUrl = document.location.origin; // get site url for requests 
}`

**Comment by samuelpatro** [comment]
I was thinking to get url of website from _config/app.php_ and **url** . What you think? @thesigae

**Comment by samuelpatro** [comment]
This cant be fixed  because we cant pass values to JS :(
