### ISSUE TITLE
Problem with the image uploading

### ISSUE THREAD

**Issue by iSaadSalman** [Samuell1/contenteditor-plugin#7]
Awesome plugin & great work.

I'm having a little trouble with uploading the image. I won't upload. I checked the network request & its giving the error "The requested URL /samuell/contenteditor/image/upload was not found on this server."

Can you please advise on this? I'm using the latest version of the plugin cloned from the git.

Thanks.

**Comment by samuelpatro** [comment]
Hey, thanks!
Can you please provide more info about october?

**Comment by iSaadSalman** [comment]
The build I'm using is 376..

**Comment by iSaadSalman** [comment]
Ok I found out that this issue happens when you have sub directory under the domain. 

Something like: localhost/cms 

When I set a virtual domain in my machine like cms.dev, it worked

**Comment by samuelpatro** [comment]
Yes, cms in sub directory is sometimes weird.

Maybe upload script is going for root and ignoring other directory
