### ISSUE TITLE
Incorrect fixture in components chain

### ISSUE THREAD

**Issue by NecroMan** [Samuell1/contenteditor-plugin#70]
It seems like a bug in the plugin. If I change fixture of one component the next one will use the same fixture except default one "div".

For example:
{% component 'contenteditor' file="header/phone.htm" fixture="p" %}
{% component 'contenteditor' file="header/title.htm" %}

The last one will be wrapped with "p" tag.

**Comment by samuelpatro** [comment]
P is default fixture if nothing is set i think.
