### ISSUE TITLE
Content editor on different plugin

### ISSUE THREAD

**Issue by rafaelsmith** [Samuell1/contenteditor-plugin#71]
Hey!
I working with plugin FAQ & Testimonials.
And I want to know If I can edit content with "content editor" with these plugins?

**Comment by samuelpatro** [comment]
Hey,
you mean like dependency for plugin? because you can make plugin dependency for theme.

**Comment by rafaelsmith** [comment]
Thanks for your replay!
I want to edit content from FAQ or Testimonials plugin with Content Editor
when I try something like that
`{% component 'contenteditor' 'FaqAll' %}`
I got error

**Comment by samuelpatro** [comment]
Iam not sure how that plugins works but do they create content files?

**Comment by rafaelsmith** [comment]
No, I think it keep the data on database and not content file

**Comment by samuelpatro** [comment]
Then it cant work.
