### ISSUE TITLE
Ajax  Controller not found

### ISSUE THREAD

**Issue by YanMyoAung** [Samuell1/contenteditor-plugin#73]
I am trying to test this plugin and I am encountering with this error. 

AJAX handler 'contenteditor::onSave' was not found.

**Comment by samuelpatro** [comment]
Hey, can you put steps when you get this issue?

 Dont forget you need to include framework & jquery scripts.

**Comment by YanMyoAung** [comment]
now It is ok @Samuell1 . Thanks for your response!
