### ISSUE TITLE
Image cropping does not work

### ISSUE THREAD

**Issue by ghost** [Samuell1/contenteditor-plugin#75]
Hello,

When I use the upload image feature, I can see an option to crop it. Tried to crop some images, but it doesn't work, the original image is always displayed.

Did I miss something ? How to make cropping to work ?

Thank you for this awesome plugin !

**Comment by samuelpatro** [comment]
Hey,

sorry but image cropping isnt implemented yet.

**Comment by ghost** [comment]
Ah ok, is it planned ?

**Comment by samuelpatro** [comment]
Yes

**Comment by samuelpatro** [comment]
Adding in 1.2.4 version.
