### ISSUE TITLE
Uncaught TypeError: $.request is not a function

### ISSUE THREAD

**Issue by dvtoid** [Samuell1/contenteditor-plugin#76]
I got this error on submitting changes by this plugin: 
Uncaught TypeError: $.request is not a function

**Comment by samuelpatro** [comment]
Hey,

that means you missing `{% framework %}` in your layout

**Comment by dvtoid** [comment]
No, i got {% framework %} tag just before {% scripts %} tag at the end of page, before </body>

**Comment by samuelpatro** [comment]
And jquery you have too?

**Comment by dvtoid** [comment]
It works if include scripts this way
```html
{% scripts %}
<script src="{{ [
    '@jquery',
    '@framework',
    'node_modules/bootstrap/dist/js/bootstrap.min.js',
    'assets/js/scripts.js'
]|theme }}">
</script>
```
Thank you much!
