### ISSUE TITLE
Override ContentEdit properties

### ISSUE THREAD

**Issue by Zmove** [Samuell1/contenteditor-plugin#77]
Hello,
Is there a clean way to override ContentEdit properties, and the modification not beeing erased on each update ? 

In my case, I'd like my users to be able to add non-breaking spaces (&nbsp;) in their  contents. It's very useful for the ponctuation. It would avoid having semicolons or question marks to go to a newline alone.

Actually, it is cleaned up and removed automatically. 
It seems that it could be kept by setting `ContentEdit.TRIM_WHITESPACE` to false. 

How could I do that ? 
Thanks.

**Comment by samuelpatro** [comment]
Hey, 
you can include this in your JS for theme, but it needs to run after contenttools is loaded.
