### ISSUE TITLE
Stuck on Save

### ISSUE THREAD

**Issue by marcoinward** [Samuell1/contenteditor-plugin#78]
Hi there, I'm having an issue where on some CMS pages, when I try save, the gear just keeps spinning for ever. 
{% framework extra %} , {% framework %} are included.

**Comment by samuelpatro** [comment]
Hey, please provide errors from console log.

**Comment by marcoinward** [comment]
Please find attached.
<img width="473" alt="Screenshot 2019-05-14 at 07 19 20" src="https://user-images.githubusercontent.com/50595545/57672499-a6213e80-7618-11e9-8583-c90e7d9dc0f0.png">

**Comment by samuelpatro** [comment]
Did you included jquery too?

**Comment by marcoinward** [comment]
Yip. The plugin works on the other pages. It seems to only have this problem on one or two pages.

**Comment by samuelpatro** [comment]
Maybe you have issue in your js code and its interfering with content editor?

**Comment by marcoinward** [comment]
On issue on that specific page? Wouldn't a js code issue cause it not to work on all pages?

**Comment by samuelpatro** [comment]
If you include custom js in one page it cant be broken only  on that one page.
