### ISSUE TITLE
Anchor - after change create element outside content block

### ISSUE THREAD

**Issue by zemiak5** [Samuell1/contenteditor-plugin#79]
Hi,

I have this code on my page
{% component 'contenteditor' file="aboutus/panel-contactus-cz.htm" class="btn-contact" fixture="a" tools="bold,italic,link" %}

content ,,aboutus/panel-contactus-cz.htm,, has code
Contact us

When I edit link for text ,,Contact us,, it wrap this link outstide a class="btn-contact"

How to achieve I can change link but class for anchor will stay same ?

**Comment by samuelpatro** [comment]
I think thats the limitation of content tools plugin it needs to wrap something where you can edit it.
