### ISSUE TITLE
Targeting Text within Divs

### ISSUE THREAD

**Issue by benparsell** [Samuell1/contenteditor-plugin#8]
Hello there!

Love what you've done so far. I'm trying to setup a section where I have text embedded within multiple div's, but I want to be able to use the entire chunk of code within the content file to avoid making a ton of content files. For example: 

`<div class="row faq-show">
          <button type="button" class="btn btn-info btn-faq" data-toggle="collapse" data-target="#demo10">Here's some text</button>
          <div id="demo10" class="collapse faq">
            I am text</div>
          </div>`
Is it possible to somehow still change the text values within the "demo10" ID with the editor?

**Comment by samuelpatro** [comment]
Hey, its not possible to change text inside tags. You need to define it in separate content files. Maybe later it can be possible :)

**Comment by samuelpatro** [comment]
@benparsell Hey, there is workaround how to allow editing of divs inside content editor. Put on **div** this attribute `data-ce-tag="p"`

**Comment by benparsell** [comment]
This is awesome — gave me a flashback to this project a year ago. Thanks for the update!
