### ISSUE TITLE
content editor not working after uploading te site to the final server

### ISSUE THREAD

**Issue by bassapguy** [Samuell1/contenteditor-plugin#80]
hello,

I build a site using the content editor on my localhost. but after uploading the site to the server the content editor pencil doesnt appear anymore. i cant figure out why it is not working anymore

**Comment by samuelpatro** [comment]
Hey,

are you logged in as a admin that has permissions for content editing?

**Comment by bassapguy** [comment]
stupid mistake thanks!!
