### ISSUE TITLE
All tools not showing. Tools  are not same as sample images

### ISSUE THREAD

**Issue by mahesh4ilapz** [Samuell1/contenteditor-plugin#82]
![image](https://user-images.githubusercontent.com/51158448/61202053-1e34df00-a704-11e9-9c6b-348a0686a1b5.png)
Showing tools like this

No table tools. div tag converted to p tags

**Comment by samuelpatro** [comment]
Hey,

i am not sure what you mean by "All tools not showing". Your image isnt same as this plugin.

**Comment by mahesh4ilapz** [comment]
Pleas remove this issue. I am so sorry to mistakenly submit this query.
