### ISSUE TITLE
div wrapper missing when not logged in

### ISSUE THREAD

**Issue by trollkotze** [Samuell1/contenteditor-plugin#83]
The plugin works by wrapping the content in an editable `<div>`, with CSS classes as provided in the "class" property. But only when one is logged in and has editing permission. When not logged in, the content is inserted as is, without the wrapping div.
Obviously, layout can look quite different between these two, which makes no sense. So I consider this a bug. The wrapper div should be there with the same CSS classes whether one is logged in or not.

**Comment by samuelpatro** [comment]
Thats how Content Tools works to allow you to edit what is inside of that div. If you want to behave like this you need to edit core js files of Content Tools.
