### ISSUE TITLE
Table properties not listed

### ISSUE THREAD

**Issue by mahesh4ilapz** [Samuell1/contenteditor-plugin#84]
![image](https://user-images.githubusercontent.com/51158448/61270161-703a3b00-a7be-11e9-896b-752abb797141.png)
Cursor is inside table cell, but tags not showing in left bottom area. other tags are showing like p, heading 

![image](https://user-images.githubusercontent.com/51158448/61270246-bf806b80-a7be-11e9-94bb-8c9044801021.png)

Can't upload image to table cell

**Comment by samuelpatro** [comment]
This looks like issue in ContentTools. Best will be to report it in their officials repository: https://github.com/GetmeUK/ContentTools/issues
