### ISSUE TITLE
Tools disappear when adding at least one fixture

### ISSUE THREAD

**Issue by vdomah** [Samuell1/contenteditor-plugin#85]
Steps to reproduce:
1. Dropping component into layout.
2. Creating line in page:
````
{% component 'contenteditor' file='home/story.htm' class="sc-iconbox__title" %}
````
all works fine here
3. {% component 'contenteditor' file='home/story_bold.htm' fixture="h3" class="sc-iconbox__title" %}
all tools except revert on go forward disapper.

**Comment by samuelpatro** [comment]
Hey, i cant reproduce this issue.

For me it works fine.
![obrázok](https://user-images.githubusercontent.com/3110002/62005616-3827e600-b136-11e9-9684-1f2cd3f16ba6.png)
