### ISSUE TITLE
Image upload doesn't work

### ISSUE THREAD

**Issue by PipeJT** [Samuell1/contenteditor-plugin#88]
Image upload on Content Editor doesn't work, I'm tried on Windows and Linux also tried on Mac and the same problem.

Error messages on browser logs be:

Linux
> VM37:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
>    at JSON.parse (<anonymous>)
>    at XMLHttpRequest.xhrComplete

Windows/Mac
> POST https://content.example.com/contenteditor/image/upload net::ERR_FAILED

**Information about installation**
October CMS Build 455 installed on a sub directory.
DNS Example of this installation: https://content.example.com/octobercms/

ContentEditor Plugin version 1.2.5

Others plugins installed

- Rainlab _Translate Plugin_
- Rainlab _Builder Plugin_
- AhmadFatoni _API Generator Plugin_
- Alxy _Captcha Plugin_
- October _Drivers Plugin_

**Comment by samuelpatro** [comment]
https://github.com/Samuell1/contenteditor-plugin/issues/67

Issue is that upload url doesnt work if ocms is installed in folder.
