### ISSUE TITLE
Question about permissions

### ISSUE THREAD

**Issue by ghost** [Samuell1/contenteditor-plugin#91]
Hello,

First, I want to thanks the module maintainer. I really like to use content editor plugin when I need to give a simple access to some part of the content of my customer websites.

However, I wonder why you chose to manage permissions by using a permission string on your plugin setting instead of a real permission using the "october way".

My problem with your actual permission system is that It give me 2 choice, but none of them is ideal : 
- If I let cms.manage_content, which seems to be the more "logical" permission to give to the user, it also have access to the CMS tab in backend, I don't want this.
- If I put something else (for example backend.access_dashboard), it works correctly. The user can use content editor on frontend (if he have access to dashboard for sure), and don't see the CMS tab, but giving the backend access right in order to edit content on frontend is not very logical.

That's why I think the best way to handle permission is to use the system provided by october. Add a new "Use content editor on frontend" permission.

If you are ok with this, I can try to create a PR.

Best regards,

Alex

**Comment by samuelpatro** [comment]
Hey, Thanks! 

It was old design that was used in Editable plugin from ocms core team, but they didnt had option to change permissions in backend.

Few days back i started reworking and refactoring things to make it more better as you can see i added now method to register permissions. 

Yes, if you can make pr you can do it, i will review it and merge :)
