### ISSUE TITLE
Div container doesn't work with editor components

### ISSUE THREAD

**Issue by chabri** [Samuell1/contenteditor-plugin#99]
Hi, I have a problem with multiple divs when I'm editing my content:

Example:

My page:
` {% component 'contenteditor' fixture="section" file="welcome.htm" %}`

My content:

```
<section class="col-sm-4">
<p>111</p>
<img alt="  height="1068" src="/myimage" width="1600" />
</section>
<section class="col-sm-4">
<p>111ecwc222ewcew</p>
<img alt="" height="1068" src="/myimage" width="1600" />
</section>

```
Then, when I want to edit, I can edit only the text elements like `<p>, <h1>,` etc... but not with the image and the ToolBar doesn't allow practically anything.

No erros in console

Any suggestion about it?

Thanks!

**Comment by samuelpatro** [comment]
This solution can maybe help: https://github.com/Samuell1/contenteditor-plugin/issues/8#issuecomment-363502156
